import apples from "../assets/images/fruits/apples.jpg";

export const fruits = [
  { id: 1, name: "Apples", price: 150, image: apples },
  { id: 2, name: "Banana", price: 40, image: "https://example.com/images/banana.jpg" },
  { id: 3, name: "Strawberry", price: 250, image: "https://example.com/images/strawberry.jpg" },
  { id: 4, name: "Oranges", price: 80, image: "https://example.com/images/orange.jpg" },
  { id: 5, name: "Blueberry", price: 300, image: "https://example.com/images/blueberry.jpg" },
  { id: 6, name: "Grapes", price: 90, image: "https://example.com/images/grapes.jpg" },
  { id: 7, name: "Pineapple", price: 60, image: "https://example.com/images/pineapple.jpg" },
  { id: 8, name: "Mango", price: 100, image: "https://example.com/images/mango.jpg" },
  { id: 9, name: "Papaya", price: 45, image: "https://example.com/images/papaya.jpg" },
  { id: 10, name: "Watermelon", price: 35, image: "https://example.com/images/watermelon.jpg" },
  { id: 11, name: "Kiwi", price: 180, image: "https://example.com/images/kiwi.jpg" },
  { id: 12, name: "Pomegranate", price: 120, image: "https://example.com/images/pomegranate.jpg" },
  { id: 13, name: "Lychee", price: 200, image: "https://example.com/images/lychee.jpg" },
  { id: 14, name: "Guava", price: 50, image: "https://example.com/images/guava.jpg" },
  { id: 15, name: "Peach", price: 150, image: "https://example.com/images/peach.jpg" },
  { id: 16, name: "Plum", price: 130, image: "https://example.com/images/plum.jpg" },
  { id: 17, name: "Cherry", price: 300, image: "https://example.com/images/cherry.jpg" },
  { id: 18, name: "Pear", price: 90, image: "https://example.com/images/pear.jpg" },
  { id: 19, name: "Apricot", price: 220, image: "https://example.com/images/apricot.jpg" },
  { id: 20, name: "Blackberry", price: 350, image: "https://example.com/images/blackberry.jpg" },
  { id: 21, name: "Fig", price: 240, image: "https://example.com/images/fig.jpg" },
  { id: 22, name: "Coconut", price: 30, image: "https://example.com/images/coconut.jpg" },
  { id: 23, name: "Lemon", price: 60, image: "https://example.com/images/lemon.jpg" },
  { id: 24, name: "Dragon Fruit", price: 300, image: "https://example.com/images/dragonfruit.jpg" },
  { id: 25, name: "Avocado", price: 180, image: "https://example.com/images/avocado.jpg" },
  { id: 26, name: "Jackfruit", price: 100, image: "https://example.com/images/jackfruit.jpg" },
  { id: 27, name: "Cantaloupe", price: 40, image: "https://example.com/images/cantaloupe.jpg" },
  { id: 28, name: "Raspberry", price: 350, image: "https://example.com/images/raspberry.jpg" },
  { id: 29, name: "Gooseberry", price: 200, image: "https://example.com/images/gooseberry.jpg" },
  { id: 30, name: "Mulberry", price: 220, image: "https://example.com/images/mulberry.jpg" },
  { id: 31, name: "Tamarind", price: 90, image: "https://example.com/images/tamarind.jpg" },
  { id: 32, name: "Persimmon", price: 150, image: "https://example.com/images/persimmon.jpg" },
  { id: 33, name: "Star Fruit", price: 180, image: "https://example.com/images/starfruit.jpg" },
  { id: 34, name: "Rambutan", price: 250, image: "https://example.com/images/rambutan.jpg" },
  { id: 35, name: "Sapodilla", price: 80, image: "https://example.com/images/sapodilla.jpg" },
  { id: 36, name: "Custard Apple", price: 120, image: "https://example.com/images/custardapple.jpg" },
  { id: 37, name: "Longan", price: 220, image: "https://example.com/images/longan.jpg" },
  { id: 38, name: "Passion Fruit", price: 200, image: "https://example.com/images/passionfruit.jpg" },
  { id: 39, name: "Pomelo", price: 100, image: "https://example.com/images/pomelo.jpg" },
  { id: 40, name: "Durian", price: 400, image: "https://example.com/images/durian.jpg" },
  { id: 41, name: "Mangosteen", price: 350, image: "https://example.com/images/mangosteen.jpg" },
  { id: 42, name: "Nectarine", price: 160, image: "https://example.com/images/nectarine.jpg" },
  { id: 43, name: "Cranberry", price: 300, image: "https://example.com/images/cranberry.jpg" },
  { id: 44, name: "Olive", price: 150, image: "https://example.com/images/olive.jpg" },
  { id: 45, name: "Quince", price: 180, image: "https://example.com/images/quince.jpg" },
  { id: 46, name: "Black Currant", price: 250, image: "https://example.com/images/blackcurrant.jpg" },
  { id: 47, name: "Red Currant", price: 250, image: "https://example.com/images/redcurrant.jpg" },
  { id: 48, name: "White Currant", price: 250, image: "https://example.com/images/whitecurrant.jpg" },
  { id: 49, name: "Jujube", price: 100, image: "https://example.com/images/jujube.jpg" },
  { id: 50, name: "Salak", price: 200, image: "https://example.com/images/salak.jpg" }
];

export const vegetables = [
  { id: 1, name: "Tomato", price: 30, image: "https://example.com/images/tomato.jpg" },
  { id: 2, name: "Potato", price: 20, image: "https://example.com/images/potato.jpg" },
  { id: 3, name: "Carrot", price: 40, image: "https://example.com/images/carrot.jpg" },
  { id: 4, name: "Broccoli", price: 80, image: "https://example.com/images/broccoli.jpg" },
  { id: 5, name: "Cauliflower", price: 50, image: "https://example.com/images/cauliflower.jpg" },
  { id: 6, name: "Spinach", price: 30, image: "https://example.com/images/spinach.jpg" },
  { id: 7, name: "Bell Pepper", price: 70, image: "https://example.com/images/bellpepper.jpg" },
  { id: 8, name: "Cabbage", price: 25, image: "https://example.com/images/cabbage.jpg" },
  { id: 9, name: "Zucchini", price: 60, image: "https://example.com/images/zucchini.jpg" },
  { id: 10, name: "Pumpkin", price: 40, image: "https://example.com/images/pumpkin.jpg" },
  { id: 11, name: "Brinjal", price: 35, image: "https://example.com/images/brinjal.jpg" },
  { id: 12, name: "Peas", price: 80, image: "https://example.com/images/peas.jpg" },
  { id: 13, name: "Onion", price: 25, image: "https://example.com/images/onion.jpg" },
  { id: 14, name: "Garlic", price: 100, image: "https://example.com/images/garlic.jpg" },
  { id: 15, name: "Ginger", price: 90, image: "https://example.com/images/ginger.jpg" },
  { id: 16, name: "Mushroom", price: 120, image: "https://example.com/images/mushroom.jpg" },
  { id: 17, name: "Lettuce", price: 50, image: "https://example.com/images/lettuce.jpg" },
  { id: 18, name: "Corn", price: 30, image: "https://example.com/images/corn.jpg" },
  { id: 19, name: "Celery", price: 40, image: "https://example.com/images/celery.jpg" },
  { id: 20, name: "Beetroot", price: 35, image: "https://example.com/images/beetroot.jpg" },
  { id: 21, name: "Radish", price: 20, image: "https://example.com/images/radish.jpg" },
  { id: 22, name: "Asparagus", price: 150, image: "https://example.com/images/asparagus.jpg" },
  { id: 23, name: "Okra", price: 40, image: "https://example.com/images/okra.jpg" },
  { id: 24, name: "Cucumber", price: 30, image: "https://example.com/images/cucumber.jpg" },
  { id: 25, name: "Bitter Gourd", price: 35, image: "https://example.com/images/bittergourd.jpg" },
  { id: 26, name: "Bottle Gourd", price: 30, image: "https://example.com/images/bottlegourd.jpg" },
  { id: 27, name: "Drumstick", price: 40, image: "https://example.com/images/drumstick.jpg" },
  { id: 28, name: "Sweet Potato", price: 60, image: "https://example.com/images/sweetpotato.jpg" },
  { id: 29, name: "Turnip", price: 25, image: "https://example.com/images/turnip.jpg" },
  { id: 30, name: "Fenugreek", price: 50, image: "https://example.com/images/fenugreek.jpg" },
  { id: 31, name: "Spring Onion", price: 40, image: "https://example.com/images/springonion.jpg" },
  { id: 32, name: "Green Beans", price: 60, image: "https://example.com/images/greenbeans.jpg" },
  { id: 33, name: "Kale", price: 90, image: "https://example.com/images/kale.jpg" },
  { id: 34, name: "Chard", price: 80, image: "https://example.com/images/chard.jpg" },
  { id: 35, name: "Arugula", price: 70, image: "https://example.com/images/arugula.jpg" },
  { id: 36, name: "Leek", price: 60, image: "https://example.com/images/leek.jpg" },
  { id: 37, name: "Artichoke", price: 140, image: "https://example.com/images/artichoke.jpg" },
  { id: 38, name: "Fennel", price: 50, image: "https://example.com/images/fennel.jpg" },
  { id: 39, name: "Coriander", price: 20, image: "https://example.com/images/coriander.jpg" },
  { id: 40, name: "Mint", price: 30, image: "https://example.com/images/mint.jpg" },
  { id: 41, name: "Basil", price: 80, image: "https://example.com/images/basil.jpg" },
  { id: 42, name: "Rosemary", price: 100, image: "https://example.com/images/rosemary.jpg" },
  { id: 43, name: "Thyme", price: 90, image: "https://example.com/images/thyme.jpg" },
  { id: 44, name: "Oregano", price: 70, image: "https://example.com/images/oregano.jpg" },
  { id: 45, name: "Dill", price: 60, image: "https://example.com/images/dill.jpg" },
  { id: 46, name: "Chives", price: 80, image: "https://example.com/images/chives.jpg" },
  { id: 47, name: "Parsley", price: 40, image: "https://example.com/images/parsley.jpg" },
  { id: 48, name: "Sage", price: 90, image: "https://example.com/images/sage.jpg" },
  { id: 49, name: "Marjoram", price: 70, image: "https://example.com/images/marjoram.jpg" },
  { id: 50, name: "Sorrel", price: 60, image: "https://example.com/images/sorrel.jpg" }
];
